### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#13]
Using an updated version of parking citations: https://files.klauspost.com/compress/parking-citations-1M.json.zst the decoder deadlocks:

```
fatal error: all goroutines are asleep - deadlock!

[... skipping irrelevant frames...]

goroutine 22 [semacquire]:
sync.runtime_Semacquire(0xc00000a058)
	C:/Go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc00000a050)
	C:/Go/src/sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0000f85a0, 0xc04283a000, 0x15c8e8c3, 0x15c8e8c3, 0x15c8e8c3, 0x5de63f39)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:91 +0x150
github.com/fwessels/simdjson-go.BenchmarkSerializeNDJSON(0xc0004161c0)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_serialize_test.go:71 +0x11d
testing.(*B).runN(0xc0004161c0, 0x1)
	C:/Go/src/testing/benchmark.go:190 +0xd3
testing.(*B).run1.func1(0xc0004161c0)
	C:/Go/src/testing/benchmark.go:230 +0x6b
created by testing.(*B).run1
	C:/Go/src/testing/benchmark.go:223 +0x84

goroutine 23 [chan send]:
github.com/fwessels/simdjson-go.find_structural_indices(0xc04284c640, 0x15c7c283, 0x15c7c283, 0xc0000f85a0, 0x0)
	C:/gopath/src/github.com/fwessels/simdjson-go/stage1_find_marks.go:66 +0x208
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func1(0xc04283a000, 0x15c8e8c3, 0x15c8e8c3, 0xc0000f85a0, 0xc00000a050)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:81 +0x50
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:80 +0xee
```

* Download and replace the file in `testdata`
* Execute `go test -test.bench=^BenchmarkSerializeNDJSON$ -test.run=None`

**Comment by klauspost** [comment]
Simpler reproducer: `{"000"`
