### ISSUE TITLE
panic: Memory corruption

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#16]
```
panic: Memory corruption -- written beyond slice capacity -- expected capacity to be larger than max values written

goroutine 55 [running]:
github.com/fwessels/simdjson-go.parse_string_simd(0xc0004800a1, 0x15, 0x1f, 0xc0000f0858, 0x1)
	C:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.go:26 +0xba
github.com/fwessels/simdjson-go.parse_string(0xc0004800a0, 0x16, 0x20, 0xc0000f0840, 0x2, 0x1, 0xc000496000)
	C:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:34 +0xad
github.com/fwessels/simdjson-go.unified_machine(0xc0004800a0, 0x16, 0x20, 0xc0000f0840, 0xc0000f0720)
	C:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:250 +0xd2f
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0xc0004800a0, 0x16, 0x20, 0xc0000f0840, 0xc0004684e0, 0xc000440180)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:85 +0x54
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:84 +0x142

Process finished with exit code 1
```

Input: `{"bimbam:1234546544j7}`

**Comment by fwessels** [comment]
An opening quote is not match by a closing quote, leading to reading beyond the end of the slice.

Similarly, if there is an uneven total number of (unescaped) quotes, the same happens.

**Comment by fwessels** [comment]
Test case fail36 should catch this: https://github.com/lemire/simdjson/blob/master/jsonchecker/fail36.json
