### ISSUE TITLE
Deadlock...

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#29]
#13 only fixes the simple case. The big example still locks up.

Stack trace:
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*B).run1(0xc0000d61c0, 0xc0000d61c0)
	C:/Go/src/testing/benchmark.go:232 +0xa5
testing.(*B).Run(0xc0000d6000, 0x7b16d1, 0x1a, 0x7c8ea0, 0x4e3200)
	C:/Go/src/testing/benchmark.go:630 +0x2bc
testing.runBenchmarks.func1(0xc0000d6000)
	C:/Go/src/testing/benchmark.go:532 +0x7f
testing.(*B).runN(0xc0000d6000, 0x1)
	C:/Go/src/testing/benchmark.go:190 +0xd3
testing.runBenchmarks(0x7b4173, 0x1f, 0xc0000046c0, 0xa5ca20, 0x3a, 0x3a, 0x40c5b0)
	C:/Go/src/testing/benchmark.go:538 +0x3a1
testing.(*M).Run(0xc000086080, 0x0)
	C:/Go/src/testing/testing.go:1123 +0x440
main.main()
	_testmain.go:236 +0x13c

goroutine 9 [semacquire]:
sync.runtime_Semacquire(0xc0000fa028)
	C:/Go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0000fa020)
	C:/Go/src/sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc00245c000, 0xc0424ca000, 0x15c8e8c3, 0x15c8e8c3, 0x15c8e8c3, 0xe693ffbd935c)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:113 +0x180
github.com/fwessels/simdjson-go.BenchmarkDeSerializeNDJSON(0xc0000d61c0)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_serialize_test.go:94 +0xc9
testing.(*B).runN(0xc0000d61c0, 0x1)
	C:/Go/src/testing/benchmark.go:190 +0xd3
testing.(*B).run1.func1(0xc0000d61c0)
	C:/Go/src/testing/benchmark.go:230 +0x6b
created by testing.(*B).run1
	C:/Go/src/testing/benchmark.go:223 +0x84

goroutine 10 [chan send]:
github.com/fwessels/simdjson-go.find_structural_indices(0xc0424db4c0, 0x15c7d403, 0x15c7d403, 0xc00245c000, 0x7c9810)
	C:/gopath/src/github.com/fwessels/simdjson-go/stage1_find_marks.go:68 +0x22e
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func1(0xc0424ca000, 0x15c8e8c3, 0x15c8e8c3, 0xc00245c000, 0xc000042220, 0xc0000fa020)
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:101 +0x54
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	C:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:100 +0x11b

Process finished with exit code 2
```

**Comment by klauspost** [comment]
Again, a simpler repro exists: `{""`

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000122d8)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0000122d0)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc00015a000, 0x3ca0000, 0x3, 0x3, 0xc000413cb8, 0xc000413d10)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:113 +0x1c6
github.com/fwessels/simdjson-go.Parse(0x3ca0000, 0x3, 0x3, 0x0, 0x7ffd99142410, 0x5, 0x2dc)
	c:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:35 +0x22b
github.com/klauspost/simdjson-fuzz.Fuzz(0x3ca0000, 0x3, 0x3, 0x3)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:14 +0xa2
go-fuzz-dep.Main(0xc000413f48, 0x1, 0x1)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:15 +0x59
exit status 2
```

**Comment by fwessels** [comment]
Benchmark test out of #13 runs fine on my machine now:
```
$ go test -test.bench=^BenchmarkSerializeNDJSON$ -test.run=None
goos: darwin
goarch: amd64
pkg: github.com/fwessels/simdjson-go
BenchmarkSerializeNDJSON/default-8                     1        1642574873 ns/op         228.60 MB/s         400 B/op          2 allocs/op
--- BENCH: BenchmarkSerializeNDJSON/default-8
    parsed_serialize_test.go:117: 375488323 (JSON) -> 85325408 (Serialized) 22.723851255422396 %
BenchmarkSerializeNDJSON/none-8                        2         533965160 ns/op         703.21 MB/s         400 B/op          2 allocs/op
--- BENCH: BenchmarkSerializeNDJSON/none-8
    parsed_serialize_test.go:117: 375488323 (JSON) -> 827488377 (Serialized) 220.37659397466803 %
    parsed_serialize_test.go:117: 375488323 (JSON) -> 827488377 (Serialized) 220.37659397466803 %
BenchmarkSerializeNDJSON/fast-8                        1        1405539244 ns/op         267.15 MB/s         400 B/op          2 allocs/op
--- BENCH: BenchmarkSerializeNDJSON/fast-8
    parsed_serialize_test.go:117: 375488323 (JSON) -> 215005638 (Serialized) 57.26027277817638 %
BenchmarkSerializeNDJSON/best-8                        1        2243985677 ns/op         167.33 MB/s    27053024 B/op        131 allocs/op
--- BENCH: BenchmarkSerializeNDJSON/best-8
    parsed_serialize_test.go:117: 375488323 (JSON) -> 42390990 (Serialized) 11.289562791543853 %
PASS
ok      github.com/fwessels/simdjson-go 21.196s

```
