### ISSUE TITLE
parse_string_simd: Memory corruption -- written beyond slice capacity

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#44]
```
panic: Memory corruption -- written beyond slice capacity -- expected capacity to be larger than max values written

goroutine 69 [running]:
github.com/fwessels/simdjson-go.parse_string_simd(0x3e327a9, 0x4e, 0x4e, 0xc0000c6018, 0x5fe8)
	c:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.go:26 +0x12d
github.com/fwessels/simdjson-go.parse_string(0x3e30000, 0x27f7, 0x27f7, 0xc0000c6000, 0xbd, 0x27a9, 0xb00)
	c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:31 +0xdd
github.com/fwessels/simdjson-go.unified_machine(0x3e30000, 0x27f7, 0x27f7, 0xc0000c6000, 0x587ef8)
	c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:281 +0xe9f
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3e30000, 0x27f7, 0x27f7, 0xc0000c6000, 0xc0000465d0, 0xc0000121f0)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:107 +0x6c
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:106 +0x1a2

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000121f8)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0000121f0)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0000c6000, 0x3e30000, 0x27f7, 0x27f7, 0xc000095cb0, 0x457590)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:116 +0x1c8
github.com/fwessels/simdjson-go.Parse(0x3e30000, 0x27f7, 0x27f7, 0x0, 0xc000095f90, 0x4647a2, 0x684ea0)
	c:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:36 +0x22b
github.com/klauspost/simdjson-fuzz.Fuzz(0x3e30000, 0x27f7, 0x27f7, 0x3)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:16 +0xbf
go-fuzz-dep.Main(0xc000095f40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64
exit status 2
```

Repro: 
[861bf6b5c2ae470681aa342b94c77a12f12837a5.gz](https://github.com/fwessels/simdjson-go/files/3950107/861bf6b5c2ae470681aa342b94c77a12f12837a5.gz)

**Comment by fwessels** [comment]
Fixed with commit 5f4fbfd
