### ISSUE TITLE
_parse_string_validate_only: Crash

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#53]
This was running through S3 select. I will see if I can get a cleaner crash.

```
unexpected fault address 0xc015090000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xc015090000 pc=0x11e3b26]

goroutine 3999 [running]:
runtime.throw(0x1b2db90, 0x5)
        c:/go/src/runtime/panic.go:774 +0x79 fp=0xc0003fdc30 sp=0xc0003fdc00 pc=0x432a29
runtime.sigpanic()
        c:/go/src/runtime/signal_windows.go:236 +0x228 fp=0xc0003fdc60 sp=0xc0003fdc30 pc=0x446738
github.com/fwessels/simdjson-go._parse_string_validate_only(0xc01508ffe3, 0xc0003fdc88, 0xc0003fdcf0, 0x1)
        c:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.s:79 +0x16 fp=0xc0003fdc68 sp=0xc0003fdc60 pc=0x11e3b26
github.com/fwessels/simdjson-go.parse_string_simd_validate_only(0xc01508ffe2, 0x16, 0x16, 0xc0003fdcf0, 0xc0003fdce7, 0xc000b18601)
        c:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.go:22 +0x5c fp=0xc0003fdca0 sp=0xc0003fdc68 pc=0x11d6a9c
github.com/fwessels/simdjson-go.parse_string(0xc014690000, 0x9ffff8, 0x9ffff8, 0xc002a20000, 0x2, 0x9fffe2, 0x434e01)
        c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:32 +0xbc fp=0xc0003fdd38 sp=0xc0003fdca0 pc=0x11df02c
github.com/fwessels/simdjson-go.unified_machine(0xc014690000, 0x9ffff8, 0x9ffff8, 0xc002a20000, 0x1bc2330)
        c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:255 +0x108f fp=0xc0003fdf58 sp=0xc0003fdd38 pc=0x11e0b1f
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0xc014690000, 0x9ffff8, 0x9ffff8, 0xc002a20000, 0xc0029aa5b0, 0xc000638010)
        c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:101 +0x54 fp=0xc0003fdfb0 sp=0xc0003fdf58 pc=0x11e2424
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0003fdfb8 sp=0xc0003fdfb0 pc=0x460c11
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
        c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:100 +0x19f
```

**Comment by fwessels** [comment]
I suspect related to #58 (writing beyond string buffer with all sorts of errors...)
