### ISSUE TITLE
parseMessage: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#55]
```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x483abe]

runtime stack:
runtime.throw(0x7253aa, 0x2a)
	runtime/panic.go:774 +0x79
runtime.sigpanic()
	runtime/signal_windows.go:227 +0x25a
runtime.gcBgMarkWorker.func1(0xc00003b080, 0xc000012cc0, 0xc00001e000)
	runtime/mgc.go:1857 +0x4e
runtime.park_m(0xc00003b080)
	runtime/proc.go:2599 +0xd6
runtime.mcall(0x48643c)
	runtime/asm_amd64.s:318 +0x5e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000012e08)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000012e00)
	sync/waitgroup.go:130 +0xb8
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc000466000, 0xc00000cdc0, 0x3a, 0x40, 0x1, 0x1)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:110 +0x409
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessageNdjson(0xc000466000, 0x4bb0000, 0x3a, 0x3b, 0x3a, 0x3b)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:121 +0x200
github.com/fwessels/simdjson-go.ParseND(0x4bb0000, 0x3a, 0x3b, 0x0, 0x3b, 0x3b, 0x1)
	c:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:61 +0x4a3
github.com/klauspost/simdjson-fuzz.Fuzz(0x4bb0000, 0x3b, 0x3b, 0x3)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:71 +0x1677
go-fuzz-dep.Main(0xc000089f40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x289
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x72

goroutine 2846 [runnable]:
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func1(0xc00000cdc0, 0x3a, 0x40, 0xc000466000, 0xc000047150, 0xc000012e00)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:94
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:94 +0x29c

goroutine 2847 [runnable]:
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0xc00000cdc0, 0x3a, 0x40, 0xc000466000, 0xc000047140, 0xc000012e00)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:100
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:100 +0x37d
exit status 2
```

**Comment by klauspost** [comment]
No longer reproduces.
