### ISSUE TITLE
parseMessage.func2: negative WaitGroup counter

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#56]
```
goroutine 7 [running]:
sync.(*WaitGroup).Add(0xc000012290, 0xffffffffffffffff)
	sync/waitgroup.go:74 +0x140
sync.(*WaitGroup).Done(...)
	sync/waitgroup.go:99
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3e60000, 0x8, 0x8, 0xc0000ae000, 0xc000046540, 0xc000012290)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:107 +0x170
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:100 +0x1cf

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000012298)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000012290)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0000ae000, 0x3e60000, 0x8, 0x8, 0x686ec0, 0x990008)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:110 +0x1f5
github.com/fwessels/simdjson-go.Parse(0x3e60000, 0x8, 0x8, 0x0, 0x457590, 0x687190, 0xc000000000)
	c:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:38 +0x240
github.com/klauspost/simdjson-fuzz.Fuzz(0x3e60000, 0x8, 0x8, 0x630)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:17 +0xbd
go-fuzz-dep.Main(0xc00009df40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64
exit status 2
```

**Comment by klauspost** [comment]
No longer reproduces.
