### ISSUE TITLE
fatal error: sync: inconsistent mutex state

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#57]
```
fatal error: sync: inconsistent mutex state

goroutine 1 [running]:
runtime.throw(0x5856a7, 0x1e)
	runtime/panic.go:774 +0x79 fp=0xc00009d800 sp=0xc00009d7d0 pc=0x42e299
sync.throw(0x5856a7, 0x1e)
	runtime/panic.go:760 +0x3c fp=0xc00009d820 sp=0xc00009d800 pc=0x42e20c
sync.(*Mutex).lockSlow(0x6a1628)
	sync/mutex.go:147 +0x15f fp=0xc00009d868 sp=0xc00009d820 pc=0x45e22f
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
sync.(*Pool).pinSlow(0x67ff80, 0x0, 0x0)
	sync/pool.go:213 +0x2a4 fp=0xc00009d908 sp=0xc00009d868 pc=0x45ed44
sync.(*Pool).pin(0x67ff80, 0x54f400, 0xc000046d80)
	sync/pool.go:206 +0x65 fp=0xc00009d930 sp=0xc00009d908 pc=0x45ea75
sync.(*Pool).Get(0x67ff80, 0x687ec0, 0x990008)
	sync/pool.go:128 +0x36 fp=0xc00009d978 sp=0xc00009d930 pc=0x45e726
fmt.newPrinter(0x194)
	c:/go/src/fmt/print.go:137 +0x50 fp=0xc00009d9a0 sp=0xc00009d978 pc=0x4d3410
fmt.Sprintln(0xc00009daa0, 0x5, 0x5, 0xc00009da50, 0x124924)
	c:/go/src/fmt/print.go:280 +0x45 fp=0xc00009d9f8 sp=0xc00009d9a0 pc=0x4d3e25
github.com/fwessels/simdjson-go.(*ParsedJson).stringByteAt(0xc00009dd88, 0x80000000000000, 0x5, 0x0, 0x8, 0x54fac0, 0xc000012d68, 0xc000012d68)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:151 +0x64f fp=0xc00009db00 sp=0xc00009d9f8 pc=0x52beff
github.com/fwessels/simdjson-go.(*Iter).StringBytes(0xc00009dd88, 0x22, 0x0, 0x0, 0x1, 0xc000012d68)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:631 +0xf1 fp=0xc00009db50 sp=0xc00009db00 pc=0x52f3e1
github.com/fwessels/simdjson-go.(*Iter).MarshalJSONBuffer(0xc00009dd88, 0xc000012d68, 0x1, 0x8, 0xc000006180, 0x0, 0x0, 0x0, 0xc00009dcb0)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:374 +0x1c26 fp=0xc00009dc90 sp=0xc00009db50 pc=0x52de76
github.com/fwessels/simdjson-go.(*Iter).MarshalJSON(...)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:350
github.com/klauspost/simdjson-fuzz.Fuzz(0x3e10000, 0xd, 0xd, 0x3)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:55 +0x781 fp=0xc00009de78 sp=0xc00009dc90 pc=0x537b31
go-fuzz-dep.Main(0xc00009df40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4 fp=0xc00009df28 sp=0xc00009de78 pc=0x47a414
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64 fp=0xc00009df60 sp=0xc00009df28 pc=0x538074
runtime.main()
	runtime/proc.go:203 +0x21e fp=0xc00009dfe0 sp=0xc00009df60 pc=0x42fc7e
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc00009dfe8 sp=0xc00009dfe0 pc=0x455ce1
exit status 2
```

**Comment by klauspost** [comment]
No longer reproduces.
