### ISSUE TITLE
_parse_string_validate_only: unexpected fault address 0x4130000

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#59]
```
unexpected fault address 0x4130000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x4130000 pc=0x5392ed]

goroutine 7940 [running]:
runtime.throw(0x582b07, 0x5)
	runtime/panic.go:774 +0x79 fp=0xc00015bd78 sp=0xc00015bd48 pc=0x42ed09
runtime.sigpanic()
	runtime/signal_windows.go:236 +0x228 fp=0xc00015bda8 sp=0xc00015bd78 pc=0x43f788
github.com/fwessels/simdjson-go._parse_string_validate_only(0x3dd208c, 0xc00015bdd0, 0xc00015be38, 0x1)
	github.com/fwessels/simdjson-go/parse_string_amd64.s:217 +0x21d fp=0xc00015bdb0 sp=0xc00015bda8 pc=0x5392ed
github.com/fwessels/simdjson-go.parse_string_simd_validate_only(0x3dd208b, 0x36, 0x36, 0xc00015be38, 0xc00015be2f, 0x405a01)
	e:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.go:22 +0x78 fp=0xc00015bde8 sp=0xc00015bdb0 pc=0x52eae8
github.com/fwessels/simdjson-go.parse_string(0x3dd0000, 0x20c1, 0x20c1, 0xc000234000, 0x2b, 0x208b, 0xc00015bf00)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:32 +0xd2 fp=0xc00015be88 sp=0xc00015bde8 pc=0x534942
github.com/fwessels/simdjson-go.unified_machine(0x3dd0000, 0x20c1, 0x20c1, 0xc000234000, 0x58da28)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:260 +0x1cdd fp=0xc00015bf58 sp=0xc00015be88 pc=0x53766d
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3dd0000, 0x20c1, 0x20c1, 0xc000234000, 0xc0000448f0, 0xc000012480)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:105 +0x6c fp=0xc00015bfb0 sp=0xc00015bf58 pc=0x53888c
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc00015bfb8 sp=0xc00015bfb0 pc=0x457001
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:104 +0x1cf

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000012488)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000012480)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc000234000, 0x3dd0000, 0x20c1, 0x20c1, 0xc000042a80, 0xca0008)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:114 +0x1f5
github.com/fwessels/simdjson-go.Parse(0x3dd0000, 0x20c1, 0x20c1, 0x0, 0x4588b0, 0xc000042d50, 0xc000000000)
	e:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:38 +0x240
github.com/klauspost/simdjson-fuzz.Fuzz(0x3dd0000, 0x20c1, 0x20c1, 0x3)
	e:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:17 +0xbf
go-fuzz-dep.Main(0xc00015df40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64
exit status 2
```

Reproducer: 
[d2a317c6dc194650d122c259d062eac666f33efd.gz](https://github.com/fwessels/simdjson-go/files/3964840/d2a317c6dc194650d122c259d062eac666f33efd.gz)

**Comment by klauspost** [comment]
It seems the same can happen in `_parse_string`:
```
unexpected fault address 0x3fe2000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x3fe2000 pc=0x5395fc]

goroutine 3734 [running]:
runtime.throw(0x582b07, 0x5)
	runtime/panic.go:774 +0x79 fp=0xc00004bd70 sp=0xc00004bd40 pc=0x42ed09
runtime.sigpanic()
	runtime/signal_windows.go:236 +0x228 fp=0xc00004bda0 sp=0xc00004bd70 pc=0x43f788
github.com/fwessels/simdjson-go._parse_string(0x3dc208c, 0xc000428d34, 0xc00004bdc8, 0x552880)
	github.com/fwessels/simdjson-go/parse_string_amd64.s:437 +0x2bc fp=0xc00004bda8 sp=0xc00004bda0 pc=0x5395fc
github.com/fwessels/simdjson-go.parse_string_simd(0x3dc208b, 0x36, 0x36, 0xc0001b4030, 0xc00004be2f)
	e:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.go:36 +0x80 fp=0xc00004bde8 sp=0xc00004bda8 pc=0x52ebb0
github.com/fwessels/simdjson-go.parse_string(0x3dc0000, 0x20c1, 0x20c1, 0xc0001b4000, 0x2b, 0x208b, 0xc00004bf00)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:50 +0x288 fp=0xc00004be88 sp=0xc00004bde8 pc=0x534af8
github.com/fwessels/simdjson-go.unified_machine(0x3dc0000, 0x20c1, 0x20c1, 0xc0001b4000, 0x58da28)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:260 +0x1cdd fp=0xc00004bf58 sp=0xc00004be88 pc=0x53766d
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3dc0000, 0x20c1, 0x20c1, 0xc0001b4000, 0xc000044860, 0xc000012480)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:105 +0x6c fp=0xc00004bfb0 sp=0xc00004bf58 pc=0x53888c
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc00004bfb8 sp=0xc00004bfb0 pc=0x457001
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:104 +0x1cf

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000012488)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000012480)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0001b4000, 0x3dc0000, 0x20c1, 0x20c1, 0x68df40, 0x2c10008)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:114 +0x1f5
github.com/fwessels/simdjson-go.Parse(0x3dc0000, 0x20c1, 0x20c1, 0x0, 0x4588b0, 0x68e210, 0xc000000000)
	e:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:38 +0x240
github.com/klauspost/simdjson-fuzz.Fuzz(0x3dc0000, 0x20c1, 0x20c1, 0x3)
	e:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:17 +0xbf
go-fuzz-dep.Main(0xc00009df40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64
exit status 2
```

Repro:
[68abeeae404aa2bf59c8f383da691b9be7b71e61.gz](https://github.com/fwessels/simdjson-go/files/3964872/68abeeae404aa2bf59c8f383da691b9be7b71e61.gz)

**Comment by fwessels** [comment]
$ ls -l 68abeeae404aa2bf59c8f383da691b9be7b71e61 
-rw-r--r--@ 1 frankw  staff  8385 Dec 16 15:52 68abeeae404aa2bf59c8f383da691b9be7b71e61
$ ls -l d2a317c6dc194650d122c259d062eac666f33efd
-rw-r--r--@ 1 frankw  staff  8385 Dec 16 15:49 d2a317c6dc194650d122c259d062eac666f33efd

8385 --> 0x20c1

```
LBB0_29:
    LONG $0x6f7ec1c4; WORD $0x0055 // vmovdqu    ymm2, yword [r13]
    LONG $0x167ffec5             // vmovdqu    yword [rsi], ymm2      <---- SIGSEGV: segmentation violation 
    LONG $0xd874edc5             // vpcmpeqb    ymm3, ymm2, ymm0
    LONG $0xcbd7fdc5             // vpmovmskb    ecx, ymm3
    LONG $0xd174edc5             // vpcmpeqb    ymm2, ymm2, ymm1
    LONG $0xf2d77dc5             // vpmovmskb    r14d, ymm2
    WORD $0x598d; BYTE $0xff     // lea    ebx, [rcx - 1]
    WORD $0x894c; BYTE $0xef     // mov    rdi, r13
    WORD $0x8544; BYTE $0xf3     // test    ebx, r14d
	JE LBB0_4
	JMP LBB0_1
```
