### ISSUE TITLE
parse_number_simd: index out of range

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#60]
```
panic: runtime error: index out of range [1] with length 1

goroutine 6 [running]:
github.com/fwessels/simdjson-go.parse_number_simd(0x3e50629, 0x1, 0x1, 0xc000049e00, 0x101, 0x4129051fd392a54d, 0x0)
	e:/gopath/src/github.com/fwessels/simdjson-go/parse_number_amd64.go:28 +0x45a
github.com/fwessels/simdjson-go.parse_number(0x3e50000, 0x62a, 0x62a, 0xc0000c0000, 0x629, 0xc000049f00, 0x0)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:60 +0x9e
github.com/fwessels/simdjson-go.unified_machine(0x3e50000, 0x62a, 0x62a, 0xc0000c0000, 0x0)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:329 +0xd85
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3e50000, 0x62a, 0x62a, 0xc0000c0000, 0xc000044010, 0xc0000120c0)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:105 +0x6c
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:104 +0x1cf

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000120c8)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0000120c0)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0000c0000, 0x3e50000, 0x62a, 0x62a, 0x68df40, 0x28f0008)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:114 +0x1f5
github.com/fwessels/simdjson-go.Parse(0x3e50000, 0x62a, 0x62a, 0x0, 0x4588b0, 0x68e210, 0xc000000000)
	e:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:38 +0x240
github.com/klauspost/simdjson-fuzz.Fuzz(0x3e50000, 0x62a, 0x62a, 0x5d4)
	e:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:17 +0xbf
go-fuzz-dep.Main(0xc0000abf40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64
exit status 2
```

Repro: 
[9f1eaba83b41deef6ec0d7441932d2a2a9e458d1.gz](https://github.com/fwessels/simdjson-go/files/3964912/9f1eaba83b41deef6ec0d7441932d2a2a9e458d1.gz)

**Comment by klauspost** [comment]
Repro 2:
[95d8460ca44b77d476fed3a452ffc706cb48f67d.gz](https://github.com/fwessels/simdjson-go/files/3964958/95d8460ca44b77d476fed3a452ffc706cb48f67d.gz)

**Comment by klauspost** [comment]
All crashes seems to have slice that is 1 too short, so it seems like an off by one.

**Comment by fwessels** [comment]
Cannot reproduce with latest build

@klauspost can you recheck if you are still seeing this error?

**Comment by klauspost** [comment]
Yep: 
[2705809f2efc6921e47a5f3c478c96fb77f8fcf6.gz](https://github.com/fwessels/simdjson-go/files/3974015/2705809f2efc6921e47a5f3c478c96fb77f8fcf6.gz)

**Comment by klauspost** [comment]
```
panic: runtime error: index out of range [1] with length 1

goroutine 8 [running]:
github.com/fwessels/simdjson-go.parse_number_simd(0x3e70647, 0x1, 0x1, 0xc000083e00, 0xc0000e0101, 0x43a6c16c16524835, 0x0)
	e:/gopath/src/github.com/fwessels/simdjson-go/parse_number_amd64.go:28 +0x45e
github.com/fwessels/simdjson-go.parse_number(0x3e70000, 0x648, 0x648, 0xc0000f2000, 0x647, 0xc000083f00, 0x0)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:60 +0x9e
github.com/fwessels/simdjson-go.unified_machine(0x3e70000, 0x648, 0x648, 0xc0000f2000, 0x0)
	e:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:329 +0xd87
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3e70000, 0x648, 0x648, 0xc0000f2000, 0xc00007c590, 0xc000012260)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:107 +0x6c
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:106 +0x1e7

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000012268)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000012260)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0000f2000, 0x3e70000, 0x648, 0x648, 0x6df260, 0x180008)
	e:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:116 +0x20d
github.com/fwessels/simdjson-go.Parse(0x3e70000, 0x648, 0x648, 0x0, 0xc0000d7cb0, 0x45b9f0, 0x6df530)
	e:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:37 +0x214
github.com/klauspost/simdjson-fuzz.Fuzz(0x3e70000, 0x648, 0x648, 0x0)
	e:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:30 +0x163
go-fuzz-dep.Main(0xc0000d7f40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64

goroutine 6 [select]:
github.com/klauspost/simdjson-fuzz.Fuzz.func1(0xc000014120)
	e:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:21 +0xd2
created by github.com/klauspost/simdjson-fuzz.Fuzz
	e:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:20 +0xdd
exit status 2
```
